ALTER TABLE IF EXISTS comments DROP COLUMN IF EXISTS tweet_id;
ALTER TABLE IF EXISTS comments DROP COLUMN IF EXISTS user_id;

ALTER  TABLE IF EXISTS comments ADD  COLUMN tweet_id UUID REFERENCES tweets(id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER  TABLE IF EXISTS comments ADD COLUMN  user_id  UUID REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE;
